[package]
name = "slimeu-mq"
version = "0.1.0"
authors = ["Rybek"]
edition = "2018"


[dependencies]

# framework
macroquad = {git="https://github.com/not-fl3/macroquad", rev="e18dd86"}
miniquad = { version = "=0.3.0-alpha.13" }

glam = {version = "0.9", features = ["scalar-math"] }

# ECS
legion = "0.3.0"

#hashmap
fxhash = "0.2.1"

# logger
log = "0.4.11"

# collision
resphys = "0.1.0"
