[package]
name = "slimeu-mq"
version = "0.1.0"
authors = ["Rybek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# framework
macroquad = {git="https://github.com/not-fl3/macroquad", rev="31cff5d"}
miniquad = { version = "=0.3.0-alpha.11" }

glam = {version = "0.8", features = ["scalar-math"] }

# ECS
legion = "0.3.0"

#hashmap
fxhash = "0.2.1"

# logger
log = "0.4.11"
